apiVersion: v1
kind: Service
metadata:
  name: pgsql-svc
  namespace: pgsql
  labels:
    app: pgsql
spec:
  clusterIP: None
  ports:
  - name: pgsql
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: pgsql