apiVersion: v1
kind: Service
metadata:
  name: pgsql-service
  namespace: pgsql
spec:
  clusterIP: None  # Headless service for stable DNS in StatefulSet
  selector:
    app: pgsql
  ports:
    - port: 5432
      protocol: TCP
      name: pgsql
      targetPort: 5432